# Android_v1.0
# åŸºç¡€è®¾ç½®
mixed-port: 7890
redir-port: 7891
tproxy-port: 1536
mode: Rule
allow-lan: true
geodata-mode: false
geo-auto-update: false
geo-update-interval: 24
unified-delay: true
tcp-concurrent: true
enable-process: true
log-level: silent
find-process-mode: always
global-client-fingerprint: chrome
external-controller: 0.0.0.0:9090
#é¢æ¿é»˜è®¤ Meta å¯é€‰ Yacd / Zash é‡å¯æ¨¡å—å³å¯åŠ è½½
external-ui: /data/adb/box_bll/panel/Meta/
secret: ""
# â€”â€”â€”â€”â€”â€”â€”â€”â€”
#####################
#ä¿®æ”¹é…ç½®æ–‡ä»¶ä¿å­˜æ—¶ï¼Œå»ºè®®é‡å¯æ¨¡å—æœåŠ¡/é‡è½½é…ç½®.
#####################

# èŠ‚ç‚¹è®°å¿†
profile:
  store-selected: true
  store-fake-ip: true
# â€”â€”â€”â€”â€”â€”â€”â€”â€”

# å—…æ¢æ¨¡å—
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "Mijia Cloud"
# â€”â€”â€”â€”â€”â€”â€”â€”â€”

# ç½‘å¡æ¨¡å—
tun:
  enable: true #true å¼€ #false å…³
  device: meta
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  strict-route: true
  auto-redirect: false
  auto-detect-interface: true
  route-exclude-address:
  - 192.168.0.0/16
  - fc00::/7
  exclude-package: # æ¸¸æˆå¡é¡¿å¯æ·»åŠ åŒ…å
    - com.tencent.mm
    - com.tencent.tmgp.sgame
    - com.ss.android.ugc.aweme
    - com.android.providers.downloads.ui
# â€”â€”â€”â€”â€”â€”â€”â€”â€”

# DNSæ¨¡å—
dns:
  enable: true
  prefer-h3: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "connect.rom.miui.com"
    - "localhost.ptlogin2.qq.com"
    - "*.market.xiaomi.com"
  default-nameserver:
    - 119.29.29.29
    - 223.6.6.6
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
# â€”â€”â€”â€”â€”â€”â€”â€”â€”

# å¥åº·æ£€æŸ¥
p: &p
  type: http
  interval: 86400
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 300
# â€”â€”â€”â€”â€”â€”â€”â€”â€”

# è®¢é˜…åœ°å€ç›¸å…³
A: &A
  filter: "^(?!.*(è®¢é˜…|ç¾¤|è´¦æˆ·|æµé‡|æœ‰æ•ˆæœŸ|æ—¶é—´|å®˜ç½‘)).*$"
  use:
  - 1.ä¸»è¦åœ°å€
  - 2.å¤‡ç”¨åœ°å€
  - 3.é¢å¤–åœ°å€

All: &All
  type: url-test
  use:
  - 1.ä¸»è¦åœ°å€
  - 2.å¤‡ç”¨åœ°å€
  - 3.é¢å¤–åœ°å€
  
proxy-providers:
  1.ä¸»è¦åœ°å€:
    <<: *p
    url: "å¼•å…¥æ‚¨çš„Clashè®¢é˜…é“¾æ¥åœ°å€"
    
  2.å¤‡ç”¨åœ°å€:
    <<: *p
    url: "å¼•å…¥æ‚¨çš„Clashè®¢é˜…é“¾æ¥åœ°å€"
  
  3.é¢å¤–åœ°å€:
    <<: *p
    url: "å¼•å…¥æ‚¨çš„Clashè®¢é˜…é“¾æ¥åœ°å€"
# â€”â€”â€”â€”â€”â€”â€”â€”â€”

proxies:
  - {name: ğŸŒ å…¨çƒç›´è¿, type: direct, udp: true}
  - {name: ğŸš« æ‹’ç»è¿æ¥, type: reject}
  - {name: ğŸŒ DNS_Hijack, type: dns}

name_proxies: &name_proxies
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1
      - â™»ï¸ å»¶è¿Ÿæœ€ä½
      - â™»ï¸ æ•…éšœè½¬ç§»
      - â™»ï¸ è´Ÿè½½å‡è¡¡
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¶å®ƒåœ°åŒº
      - ğŸŒ å…¨çƒç›´è¿
# â€”â€”â€”â€”â€”â€”â€”â€”â€”

proxy-groups:
  - name: ğŸ¯ æ€»æ¨¡å¼
    <<: *name_proxies

  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ å»¶è¿Ÿæœ€ä½
      - ğŸŒ å…¨çƒç›´è¿
    <<: *A

  - name: â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1
    type: select
    proxies:
      - â™»ï¸ å»¶è¿Ÿæœ€ä½
      - ğŸŒ å…¨çƒç›´è¿
    <<: *A

  - name: â™»ï¸ å»¶è¿Ÿæœ€ä½
    type: url-test
    <<: *A
  
  - name: â™»ï¸ æ•…éšœè½¬ç§»
    type: fallback
    <<: *A
  
  - name: â™»ï¸ è´Ÿè½½å‡è¡¡
    type: load-balance
    strategy: round-robin
    <<: *A

  - name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
    <<: *name_proxies

  - name: ğŸ¤– OpenAI
    <<: *name_proxies

  - name: ğŸ¬ æ²¹ç®¡åª’ä½“
    <<: *name_proxies

  - name: ğŸ“¸ TikTok
    <<: *name_proxies

  - name: ğŸ“± è„¸ä¹¦ç¤¾äº¤
    <<: *name_proxies

  - name: ğŸ“¹ å¥ˆé£åª’ä½“
    <<: *name_proxies

  - name: ğŸ“¢ è°·æ­ŒæœåŠ¡
    <<: *name_proxies

  - name: ğŸ“£ è°·æ­Œæ¨é€
    <<: *name_proxies

  - name: ğŸ® Discord
    <<: *name_proxies

  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    <<: *name_proxies

  - name: ğŸ è‹¹æœæœåŠ¡
    <<: *name_proxies

  - name: ğŸ¹ ç½‘æ˜“éŸ³ä¹
    <<: *name_proxies

  - name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies:
      - ğŸš« æ‹’ç»è¿æ¥
      - ğŸŒ å…¨çƒç›´è¿

  - name: ğŸ‹ æ¼ç½‘ä¹‹é±¼
    <<: *name_proxies

  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    filter: "^(?=.*(æ¸¯|HK|hk|Hong Kong|HongKong|hongkong)).*$"
    <<: *All

  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    filter: "^(?=.*(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan)).*$"
    <<: *All

  - name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    filter: "^(?=.*(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)).*$"
    <<: *All

  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
    filter: "^(?=.*(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)).*$"
    <<: *All

  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
    filter: "^(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)).*$"
    <<: *All

  - name: ğŸŒ å…¶å®ƒåœ°åŒº
    filter: "^(?!.*(æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan|æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|ç¾|ç½‘æ˜“|Netease|è®¢é˜…|ç¾¤|è´¦æˆ·|æµé‡|æœ‰æ•ˆæœŸ|æ—¶é—´|å®˜ç½‘)).*$"
    <<: *All
# â€”â€”â€”â€”â€”â€”â€”â€”â€”

rule-anchor:
  RuleDefault: &RuleDefault
    {type: http, behavior: classical, format: text, interval: 86400}
  Domain: &Domain
    {type: http, behavior: domain, format: mrs, interval: 86400}
  IP: &IP
    {type: http, behavior: ipcidr, format: mrs, interval: 86400}
# â€”â€”â€”â€”â€”â€”â€”â€”â€”

rule-providers:
  CN_IP:
    <<: *IP
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"
    
  private_Lan:
    <<: *IP
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"

  CN_åŸŸå:
    <<: *Domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"

  category-ads-all:
    <<: *Domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads-all.mrs"

  TikTok:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list"

  Facebook:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list"

  Telegram:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list"

  YouTube:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list"

  Google:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list"

  GoogleFCM:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GoogleFCM/GoogleFCM.list"

  Microsoft:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list"

  Apple:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list"

  OpenAI:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list"

  Netflix:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Netflix/Netflix.list"

  Discord:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Discord/Discord.list"

  NetEaseMusic:
    <<: *RuleDefault
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/NetEaseMusic/NetEaseMusic.list"
# â€”â€”â€”â€”â€”â€”â€”â€”â€”

rules:
  - DST-PORT,53,ğŸŒ DNS_Hijack
  - AND,((PROCESS-NAME,mihomo),(NOT,((IN-TYPE,inner)))),REJECT
  - AND,((PROCESS-NAME,clash),(NOT,((IN-TYPE,inner)))),REJECT
  - RULE-SET,NetEaseMusic,ğŸ¹ ç½‘æ˜“éŸ³ä¹
  - RULE-SET,Discord,ğŸ® Discord
  - RULE-SET,TikTok,ğŸ“¸ TikTok
  - RULE-SET,YouTube,ğŸ¬ æ²¹ç®¡åª’ä½“
  - RULE-SET,Netflix,ğŸ“¹ å¥ˆé£åª’ä½“
  - RULE-SET,Facebook,ğŸ“± è„¸ä¹¦ç¤¾äº¤
  - RULE-SET,OpenAI,ğŸ¤– OpenAI
  - RULE-SET,Google,ğŸ“¢ è°·æ­ŒæœåŠ¡
  - RULE-SET,GoogleFCM,ğŸ“£ è°·æ­Œæ¨é€
  - RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,Telegram,ğŸ“² ç”µæŠ¥ä¿¡æ¯
  - RULE-SET,category-ads-all,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,CN_åŸŸå,ğŸŒ å…¨çƒç›´è¿
  - RULE-SET,CN_IP,ğŸŒ å…¨çƒç›´è¿,no-resolve
  - RULE-SET,private_Lan,ğŸŒ å…¨çƒç›´è¿,no-resolve
  - MATCH,ğŸ‹ æ¼ç½‘ä¹‹é±¼
# â€”â€”â€”â€”â€”â€”â€”â€”â€”